### ISSUE TITLE
Excessive debug logging to stdout

### ISSUE THREAD

**Issue by che-vgik** [saikatharryc/pm2-prometheus-exporter#10]
it write to stdout big amount of logs, cannot disable it.
-----
also thereis anerror in the end of every message
...end of message begin
pm_id: 11,  monit: { memory: 44871680, cpu: 0 } } undefined '>>>>>>'","timestamp":"2019-04-01T16:04:47.079Z","type":"out","process_id":0,"app_name":"pm2-metrics"}
[stdout.log](https://github.com/saikatharryc/pm2-prometheus-exporter/files/3030381/stdout.log)
is there a way to disable it by setting variables?

**Comment by che-vgik** [comment]
in 1.0.15 there is another error:
0|pm2-metr | TypeError: logger.error is not a function
0|pm2-metr |     at pm2c.then.catch.err (/media/data/pm2/.pm2/modules/pm2-metrics/node_modules/pm2-metrics/exporter.js:111:14)
0|pm2-metr |     at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by saikatharryc** [comment]
#11

**Comment by saikatharryc** [comment]
@che-vgik hi, you can either use the `1.0.14` or else `1.0.16` . if you are still in .`1.0.15` please upgrade or degrade.
we are doing some sort up update in logging mechanism, if you find anything else in future, feel free to raise PR.

**Comment by che-vgik** [comment]
@saikatharryc i've updated to 1.0.16.
the main problem that it fails to parse some metrics and add output to stdout with error. 1 output per instance is about 20kb, 60 instances, every 15 second scraping.
i've disabled logging by adding `pm2 conf pm2-metrics:pm_out_log_path /dev/null && pm2 conf pm2-metrics:pm_err_log_path /dev/null` but it hardcoded in code to output errored response to stdout.
i want to be able disable it, or maybe **fix**, because 2gb of logs every day is expensive for space.
see the attach of pm2 stdout for more info.
[stdout log.txt](https://github.com/saikatharryc/pm2-prometheus-exporter/files/3033473/stdout.log.txt)

**Comment by saikatharryc** [comment]
@che-vgik  you mean, because of logging in console the error is coming up right?

**Comment by che-vgik** [comment]
>you mean, because of logging in console the error is coming up right?
@saikatharryc, i even don't know, is this error or just bug in logging, because i've recieve some metrics even with this error to stdout.
example of recieved metrics (one instance of app is running)

[pm2-metrics_output.txt](https://github.com/saikatharryc/pm2-prometheus-exporter/files/3033596/pm2-metrics_output.txt)

**Comment by saikatharryc** [comment]
okay, just to make it clear ,
@che-vgik  
can you also confirm me this few things?
1> The Issue you are facing , that you can only see when you check the log by doing something similer to `pm2 log <NAME>` right?
2> even if the issue comes, are you still receving proper expected output in `:9209/metrics` endpoint ?

**Comment by che-vgik** [comment]
dear @saikatharryc, i'll try to explain.
1. we've starting docker container with something like that
`exec su node -s /bin/sh -c "NODE_ENV=$NODE_ENV pm2-runtime start $JS_PATH -i ${INSTANCES} --env ${NODE_ENV} --node-args ${NODE_ARGS}" >>${LOG_DIR}/app_out.log 2>>${LOG_DIR}/app_error.log`
in app_out.log there is big amount of messages like https://github.com/saikatharryc/pm2-prometheus-exporter/files/3033473/stdout.log.txt, even when `pm2 conf pm2-metrics:pm_out_log_path /dev/null && pm2 conf pm2-metrics:pm_err_log_path /dev/null` .
and this file grows very fast, about 20kb per 1 server
i've added output in attachment with command `pm2 log pm2-metrics`
[pm2_log_pm2-metrics.txt](https://github.com/saikatharryc/pm2-prometheus-exporter/files/3034939/pm2_log_pm2-metrics.txt)
2. yes, we've recieve expected output, but i'm not sure that all metrics are inside. you can review :9209/metrics in https://github.com/saikatharryc/pm2-prometheus-exporter/files/3033596/pm2-metrics_output.txt
