### ISSUE TITLE
when exec "pm2 kill",the pm2-metrics will not start automatically

### ISSUE THREAD

**Issue by AlliotTech** [saikatharryc/pm2-prometheus-exporter#60]
because of network problem, i have to use "git clone && npm install " and push the static files into my server ,and "pm2 install ." to run.
 
but when i use "pm2 kill " ,then "pm2 status "  .the pm2-metrics will no start automatically.  

if i run with  "pm2 install pm2-metrics" , the pm2-metrics will start automatically after i run "pm2 kill && pm2 status"... 

Can you tell me how I can make the previous mode start automatically

**Comment by saikatharryc** [comment]
I believe you have some customization in place? please confirm with me.

If I understood the issue correctly, 

you usually run pm2-metrics by cloning from the git repo and not by `pm2 install pm2-metrics`

and when you usually do `pm2 kill` it just stops and does not spawn back? (when started from the git cloned repo)
and even though you do `pm2 kill` it just spawns back, when you did `pm2 install pm2-metrics` to start the `pm2-metrics`


am I correct on the above?

**Comment by AlliotTech** [comment]
Thanks for your reply.
yes~ you are right~ 
That is to say, I used `pm2 install pm2-matrics` to install online. After `pm2 kill`, it can spawn back automatically.
but if I use:  
``` shell 
    $ git clone https://github.com/saikatharryc/pm2-prometheus-exporter.git
    $ npm install
    $ pm2 start exporter.js --name pm2-metrics
```
like this way, After I execute `pm2 kill` to  kill it, it won't restart properly.

**Comment by saikatharryc** [comment]
well, I see the problem, modules are designed to keep like that. although.
did you try using `pm2 restart all`?
or maybe `pm2 reload all` (if cluster mode)
in this way, you don't have to kill the processes completely. and the service will respawn with another PID.

**Comment by AlliotTech** [comment]
due to my own node project is use `pm2 kill` to redeployment to avoid some other problems. so I can't use `pm2 restart` to restart all...

**Comment by saikatharryc** [comment]
would you mind sharing the configuration details for another service that you run, which spawns automatically even you do `pm2 kill`?
I can then just figure out if I'm missing out something in the configuration, it's just the pm2 thingy.
