### ISSUE TITLE
Scraping from 2 prometheus servers in parallel causes gaps in metrics 

### ISSUE THREAD

**Issue by fllaca** [saikatharryc/pm2-prometheus-exporter#7]
I have 2 prometheus servers monitoring my system, both at the same time, so I don't loose metrics if any of them goes down. But they seem to "collide" somehow when scraping pm2 metrics using this module, causing big gaps in the metrics.
![image](https://user-images.githubusercontent.com/14851307/55257426-243fa680-5260-11e9-85ab-007b7ce8b4b4.png)
But then in the other instance you see the "complement" gaps for the same metric:
![image](https://user-images.githubusercontent.com/14851307/55257505-5b15bc80-5260-11e9-9881-4b872475da91.png)

It seems that this exporter doesn't support 2 prometheus instances being scraping at the same time. Have you found this issue before? I suspect that maybe it's related with persistent TCP connections from prometheus, but I don't have enough evidence.

**Comment by saikatharryc** [comment]
Hi @fllaca
i never tried to use 2 prom with same target at a time. 
`pm2-metrics` just serves the metrics when called the end-point. rest of part is handled by prometheus it self.

can you mention this following:
* which version you are using of `pm2-metrics`?
* how many restarts happened  for `pm2-metrics` [check with `pm2 status`] ?
* can you post a `pm2 log pm2-metrics --err` incase there is more than *1* restart ?

**Comment by fllaca** [comment]
Hi @saikatharryc ! Thanks for the quick response. Here you have the restarts and version, and error logs as well:

```
Module
┌─────────────┬────┬─────────┬───────┬────────┬─────────┬─────┬───────────┬────────┐
│ Module      │ id │ version │ pid   │ status │ restart │ cpu │ memory    │ user   │
├─────────────┼────┼─────────┼───────┼────────┼─────────┼─────┼───────────┼────────┤
│ pm2-metrics │ 15 │ 1.0.13  │ 12631 │ online │ 0       │ 0%  │ 52.9 MB   │ adhara │
└─────────────┴────┴─────────┴───────┴────────┴─────────┴─────┴───────────┴────────┘
```

```
adhara@ip-10-1-0-208:~$ pm2 log pm2-metrics --err
[TAILING] Tailing last 15 lines for [pm2-metrics] process (change the value with --lines option)
/home/adhara/.pm2/logs/pm2-metrics-error.log last 15 lines:
15|pm2-met | (node:12631) DeprecationWarning: prom-client - Passing a non-object to metrics constructor is deprecated
```

**Comment by fllaca** [comment]
@saikatharryc seems that using (and clearing) the global prom registry in every request was causing the issue when calling the exporter concurrently. I submitted this PR (#8) with a fix, building and using a registry in each request other than the global one, after deploying this change I don't see those gaps anymore.

**Comment by saikatharryc** [comment]
great, that is a nice catch. thanks for improving the package. i'm pushing this to new version.
